name: Install Qt
description: Install Qt 6 with the shader tools module and dependency caching

inputs:
  version:
    description: Qt version to install, e.g. 6.8.1
    required: true
  arch:
    description: Qt arch identifier, e.g. linux_gcc_64
    required: true

runs:
  using: composite
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@a9c63c7c123f3069cff414e7e482d95dfa9d8125 # v4
      with:
        version: ${{ inputs.version }}
        arch: ${{ inputs.arch }}
        modules: 'qtshadertools'
        cache: true
