name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz libudev-dev

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67 # v6

      - name: Install Qt
        uses: ./.github/actions/install-qt
        with:
          version: '6.8.1'
          arch: linux_gcc_64

      - name: Install KF6 IdleTime
        uses: ./.github/actions/install-kf6-idletime

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=ON -DBUILD_TESTING=OFF

      - name: Generate Doxygen documentation
        run: cmake --build build --target docs

      - name: Check generated files
        run: ls -lR build/docs/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
          publish_branch: gh-pages
          keep_files: true
