name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
        arch: linux_gcc_64
        modules: 'qtshadertools'
        cache: true

    - name: Configure
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=ON -DBUILD_TESTING=OFF

    - name: Generate Doxygen documentation
      run: cmake --build build --target docs

    - name: Check generated files
      run: ls -lR build/docs/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/html
        publish_branch: gh-pages
